include $(TLR_BASE)/build/rds00008.mk

.PHONY: all clean install

all:
	#cd common; make all;
	#cd cm-manager-mm; make all;
	#cd cmm-manager; make all;
	#cd cm-manager; make all;
	cd modem-manager; make all;
clean:
	#cd common; make clean;
	#cd cm-manager-mm; make clean;
	#cd cmm-manager; make clean;
	#cd cm-manager; make clean;
	cd modem-manager; make clean;
