#ifndef _CM_MODEM_STATE_
#define _CM_MODEM_STATE_

typedef enum {
	CM_MODEM_STATE_NONE = 0,
	CM_MODEM_STATE_DISABLED,
	CM_MODEM_STATE_ENABLED,
	CM_MODEM_STATE_REGISTERED,
	CM_MODEM_STATE_CONNECTED,
	CM_MODEM_STATE_DISCONNECTED
} cm_modem_state_t;

#endif /* _CM_MODEM_STATE_ */
